In [1]:
!python --version

Python 3.10.14


In [2]:
import gc
gc.collect()

0

In [3]:
in_colab = False

In [4]:
if in_colab:

  from google.colab import drive
  drive.mount("/content/drive/", force_remount = True)

In [5]:
if in_colab:
  !pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 #-f https://download.pytorch.org/whl/cu121

In [6]:
if in_colab:
  !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.3.0+cpu.html#torch-2.3.0+cu121.html

In [7]:
if in_colab:
  !pip install torch_geometric

In [8]:
if in_colab:
  import locale
  def getpreferredencoding(do_setlocale = True):
      return "UTF-8"
  locale.getpreferredencoding = getpreferredencoding
  !pip install pygod

In [9]:
import torch
torch.__version__

'2.4.0+cu121'

In [10]:
import torch_geometric
print(torch_geometric.typing.WITH_PYG_LIB)

True


In [11]:
if in_colab:
  %cd "/content/drive/MyDrive/Colab Notebooks/GraphOutlierDetection"

In [12]:
!dir

 Il volume nell'unit… C Š Windows
 Numero di serie del volume: 123E-4DB7

 Directory di C:\Users\ugo-c\Desktop\ADIN

13/11/2024  11:45    <DIR>          .
13/11/2024  10:02    <DIR>          ..
13/11/2024  11:15    <DIR>          .ipynb_checkpoints
13/11/2024  11:56    <DIR>          .virtual_documents
13/11/2024  11:56    <DIR>          .vs
13/11/2024  11:49    <DIR>          adin
17/10/2024  15:14    <DIR>          assets
16/10/2024  14:20        10.037.628 gaan.pt
13/11/2024  11:08         5.063.500 gnn.ipynb
18/10/2024  19:15         5.063.500 god.ipynb
21/10/2024  14:23           459.769 god_isn.ipynb
26/09/2024  14:50             1.088 LICENSE
13/11/2024  11:45            86.438 main.py
30/09/2024  09:59             1.197 README.md
30/09/2024  09:47               297 requirements.txt
30/09/2024  09:47               297 requirementscuda.txt
30/09/2024  09:47               152 requirementstorch.txt
30/09/2024  09:47               145 requirementstorchcuda.txt
13/11/2024  11:01    <

In [13]:
import os
cwd = os.getcwd()
sep = os.sep
datapath = cwd + sep + "Dataset" + sep
datapath

'C:\\Users\\ugo-c\\Desktop\\ADIN\\Dataset\\'

In [15]:
expr_filename = cwd + sep + "use_case"+sep+"data"+sep+"bladder_cancer"+sep+"gene_expression_data_preprocessed.csv"
#expr_filename = cwd + sep + "use_case"+sep+"data"+sep+"celiac"+sep+"preprocessed_data.csv"
output = cwd + sep + "ouput.png"

In [16]:
import pandas as pd

expr = pd.read_csv(expr_filename, index_col = 0)
expr

ATP2A1     SLMAP     MEOX2     HOXD3    ZNF398     PANX1  \
GSM928410  0.663336  0.529598  0.162563  0.383908  0.096852  0.137029   
GSM928411  0.732851  0.637804  0.087245  0.364565  0.100989  0.104867   
GSM928412  0.731909  0.467229  0.151392  0.410514  0.105380  0.118404   
GSM928413  0.756482  0.712974  0.125020  0.438931  0.072189  0.117990   
GSM928414  0.627336  0.374188  0.072009  0.564686  0.083819  0.094375   
GSM928415  0.668793  0.394460  0.122008  0.392940  0.084649  0.105771   
GSM928416  0.426092  0.256789  0.158605  0.744571  0.093180  0.117594   
GSM928417  0.543068  0.161934  0.095487  0.781442  0.045247  0.119621   
GSM928418  0.806099  0.783551  0.182352  0.764526  0.086602  0.122421   
GSM928419  0.535368  0.125626  0.101444  0.811086  0.027037  0.069629   
GSM928420  0.703619  0.676400  0.111034  0.846040  0.037037  0.118240   
GSM928421  0.817144  0.093566  0.119262  0.794505  0.022453  0.231460   
GSM928422  0.409728  0.093750  0.088316  0.805207  0.015399  0.108503   
GSM928423  0.543978  0.189580  0.109502  0.705171  0.033869  0.220051   
GSM928424  0.832374  0.129283  0.031621  0.798701  0.018344  0.089821   
GSM928425  0.815578  0.315857  0.046209  0.871397  0.018025  0.070097   
GSM928426  0.418700  0.074661  0.040767  0.823890  0.015405  0.054142   
GSM928427  0.750107  0.308633  0.022222  0.841576  0.014033  0.037842   
GSM928428  0.733186  0.130307  0.042095  0.802706  0.015738  0.071776   
GSM928429  0.604937  0.100124  0.033127  0.841069  0.018455  0.052406   
GSM928430  0.437868  0.140084  0.519438  0.684985  0.016173  0.076557   
GSM928431  0.298159  0.138758  0.058877  0.752970  0.024597  0.052569   
GSM928432  0.328170  0.076230  0.345729  0.778197  0.025442  0.065034   
GSM928433  0.184375  0.109300  0.026707  0.839303  0.018748  0.086138   

              COX8C     IMPA2      TTC8  FLJ35816  ...    ZFP2.1   CST9L.1  \
GSM928410  0.971139  0.039016  0.029115  0.530092  ...  0.174781  0.759511   
GSM928411  0.968545  0.046063  0.035143  0.592064  ...  0.094503  0.747333   
GSM928412  0.961028  0.043965  0.031300  0.554694  ...  0.110763  0.764336   
GSM928413  0.971448  0.044214  0.031502  0.587456  ...  0.052426  0.775798   
GSM928414  0.968190  0.028884  0.018645  0.596519  ...  0.043576  0.792672   
GSM928415  0.973028  0.041213  0.023148  0.579087  ...  0.113668  0.757963   
GSM928416  0.971882  0.050376  0.049978  0.508073  ...  0.052173  0.777005   
GSM928417  0.964217  0.040574  0.030213  0.378127  ...  0.051021  0.745892   
GSM928418  0.963932  0.043778  0.030160  0.501038  ...  0.060801  0.801456   
GSM928419  0.970158  0.032499  0.022672  0.557364  ...  0.042587  0.790621   
GSM928420  0.978038  0.029411  0.024753  0.489507  ...  0.031715  0.524165   
GSM928421  0.982106  0.031482  0.013398  0.573627  ...  0.022869  0.814041   
GSM928422  0.978841  0.026527  0.016016  0.512338  ...  0.030848  0.775920   
GSM928423  0.976979  0.023748  0.011903  0.613839  ...  0.043739  0.802150   
GSM928424  0.980335  0.022257  0.009273  0.518569  ...  0.038415  0.821270   
GSM928425  0.981824  0.025346  0.009612  0.579383  ...  0.019224  0.835004   
GSM928426  0.982683  0.024076  0.009506  0.470287  ...  0.020391  0.786767   
GSM928427  0.986313  0.021968  0.009482  0.573926  ...  0.021235  0.826842   
GSM928428  0.979202  0.019832  0.010430  0.534893  ...  0.022399  0.815613   
GSM928429  0.977567  0.023292  0.013491  0.562744  ...  0.021738  0.832677   
GSM928430  0.978034  0.023050  0.011165  0.481810  ...  0.042978  0.518412   
GSM928431  0.984636  0.024411  0.012639  0.462050  ...  0.025951  0.793100   
GSM928432  0.976318  0.022026  0.015277  0.549231  ...  0.016248  0.747001   
GSM928433  0.984204  0.015195  0.006160  0.437519  ...  0.026670  0.155150   

           C11orf24.1    QPRT.1  LEPRE1.1   GNAS.29    RPN1.1   CYB5A.1  \
GSM928410    0.103661  0.200964  0.200289  0.397994  0.031667  0.116547   
GSM928411    0.085542  0.224168  0.103062  0.376746  0.028174  0.069490   
GSM928412  

In [17]:
clinic = pd.DataFrame(expr["Target"])
clinic

Target
GSM928410       0
GSM928411       0
GSM928412       0
GSM928413       0
GSM928414       0
GSM928415       0
GSM928416       1
GSM928417       1
GSM928418       1
GSM928419       1
GSM928420       1
GSM928421       1
GSM928422       1
GSM928423       1
GSM928424       1
GSM928425       1
GSM928426       1
GSM928427       1
GSM928428       1
GSM928429       1
GSM928430       1
GSM928431       1
GSM928432       1
GSM928433       1

In [18]:
expr = expr.drop("Target", axis = 1)
expr

ATP2A1     SLMAP     MEOX2     HOXD3    ZNF398     PANX1  \
GSM928410  0.663336  0.529598  0.162563  0.383908  0.096852  0.137029   
GSM928411  0.732851  0.637804  0.087245  0.364565  0.100989  0.104867   
GSM928412  0.731909  0.467229  0.151392  0.410514  0.105380  0.118404   
GSM928413  0.756482  0.712974  0.125020  0.438931  0.072189  0.117990   
GSM928414  0.627336  0.374188  0.072009  0.564686  0.083819  0.094375   
GSM928415  0.668793  0.394460  0.122008  0.392940  0.084649  0.105771   
GSM928416  0.426092  0.256789  0.158605  0.744571  0.093180  0.117594   
GSM928417  0.543068  0.161934  0.095487  0.781442  0.045247  0.119621   
GSM928418  0.806099  0.783551  0.182352  0.764526  0.086602  0.122421   
GSM928419  0.535368  0.125626  0.101444  0.811086  0.027037  0.069629   
GSM928420  0.703619  0.676400  0.111034  0.846040  0.037037  0.118240   
GSM928421  0.817144  0.093566  0.119262  0.794505  0.022453  0.231460   
GSM928422  0.409728  0.093750  0.088316  0.805207  0.015399  0.108503   
GSM928423  0.543978  0.189580  0.109502  0.705171  0.033869  0.220051   
GSM928424  0.832374  0.129283  0.031621  0.798701  0.018344  0.089821   
GSM928425  0.815578  0.315857  0.046209  0.871397  0.018025  0.070097   
GSM928426  0.418700  0.074661  0.040767  0.823890  0.015405  0.054142   
GSM928427  0.750107  0.308633  0.022222  0.841576  0.014033  0.037842   
GSM928428  0.733186  0.130307  0.042095  0.802706  0.015738  0.071776   
GSM928429  0.604937  0.100124  0.033127  0.841069  0.018455  0.052406   
GSM928430  0.437868  0.140084  0.519438  0.684985  0.016173  0.076557   
GSM928431  0.298159  0.138758  0.058877  0.752970  0.024597  0.052569   
GSM928432  0.328170  0.076230  0.345729  0.778197  0.025442  0.065034   
GSM928433  0.184375  0.109300  0.026707  0.839303  0.018748  0.086138   

              COX8C     IMPA2      TTC8  FLJ35816  ...   A2ML1.1    ZFP2.1  \
GSM928410  0.971139  0.039016  0.029115  0.530092  ...  0.626678  0.174781   
GSM928411  0.968545  0.046063  0.035143  0.592064  ...  0.671998  0.094503   
GSM928412  0.961028  0.043965  0.031300  0.554694  ...  0.602572  0.110763   
GSM928413  0.971448  0.044214  0.031502  0.587456  ...  0.627324  0.052426   
GSM928414  0.968190  0.028884  0.018645  0.596519  ...  0.710886  0.043576   
GSM928415  0.973028  0.041213  0.023148  0.579087  ...  0.658017  0.113668   
GSM928416  0.971882  0.050376  0.049978  0.508073  ...  0.221204  0.052173   
GSM928417  0.964217  0.040574  0.030213  0.378127  ...  0.268238  0.051021   
GSM928418  0.963932  0.043778  0.030160  0.501038  ...  0.265713  0.060801   
GSM928419  0.970158  0.032499  0.022672  0.557364  ...  0.141304  0.042587   
GSM928420  0.978038  0.029411  0.024753  0.489507  ...  0.163198  0.031715   
GSM928421  0.982106  0.031482  0.013398  0.573627  ...  0.151882  0.022869   
GSM928422  0.978841  0.026527  0.016016  0.512338  ...  0.227843  0.030848   
GSM928423  0.976979  0.023748  0.011903  0.613839  ...  0.227618  0.043739   
GSM928424  0.980335  0.022257  0.009273  0.518569  ...  0.132613  0.038415   
GSM928425  0.981824  0.025346  0.009612  0.579383  ...  0.316190  0.019224   
GSM928426  0.982683  0.024076  0.009506  0.470287  ...  0.140426  0.020391   
GSM928427  0.986313  0.021968  0.009482  0.573926  ...  0.145121  0.021235   
GSM928428  0.979202  0.019832  0.010430  0.534893  ...  0.201235  0.022399   
GSM928429  0.977567  0.023292  0.013491  0.562744  ...  0.111266  0.021738   
GSM928430  0.978034  0.023050  0.011165  0.481810  ...  0.161789  0.042978   
GSM928431  0.984636  0.024411  0.012639  0.462050  ...  0.201561  0.025951   
GSM928432  0.976318  0.022026  0.015277  0.549231  ...  0.132105  0.016248   
GSM928433  0.984204  0.015195  0.006160  0.437519  ...  0.149824  0.026670   

            CST9L.1  C11orf24.1    QPRT.1  LEPRE1.1   GNAS.29    RPN1.1  \
GSM928410  0.759511    0.103661  0.200964  0.200289  0.397994  0.031667   
GSM928411  0.747333    0.085542  0.224168  0.103062  0.376746  0.028174   
GSM928412  

In [19]:
import torch
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

In [20]:
import torch
import numpy as np

def parse_edges(edge_list):
    source_nodes = []
    target_nodes = []
    node_mapping = {}
    next_index = 0

    for edge in edge_list:
        source, target = edge.split('_')
        #if source == target:
        #    continue
        if source not in node_mapping:
            node_mapping[source] = next_index
            next_index += 1
        if target not in node_mapping:
            node_mapping[target] = next_index
            next_index += 1

        source_nodes.append(node_mapping[source])
        target_nodes.append(node_mapping[target])

    return source_nodes, target_nodes, node_mapping

def create_edge_index(source_nodes, target_nodes):
    edge_list = np.array([source_nodes, target_nodes], dtype=np.int64)
    edge_index = torch.LongTensor(edge_list)
    return edge_index

In [21]:
exp_values = torch.tensor(expr.values).to(device)
corr = torch.corrcoef(exp_values)
corr.shape

torch.Size([24, 24])

In [22]:
from torch.nn.functional import cosine_similarity

In [23]:
n = len(exp_values)
sim_matrix = np.zeros((n, n))
for i, elem1 in enumerate(exp_values):
  for j, elem2 in enumerate(exp_values):
    sim = cosine_similarity(elem1, elem2, dim = 0).item()
    sim_matrix[i][j] = sim

In [24]:
sim_matrix

array([[1.        , 0.98716688, 0.9877132 , 0.9790296 , 0.97098654,
        0.98624697, 0.90942817, 0.89622349, 0.9241625 , 0.92965189,
        0.86237835, 0.89938386, 0.91207667, 0.93741412, 0.93798899,
        0.92412267, 0.8871658 , 0.91755491, 0.90285488, 0.90231683,
        0.88125474, 0.90061897, 0.89006381, 0.83132263],
       [0.98716688, 1.        , 0.99625498, 0.98652225, 0.98212716,
        0.99610172, 0.91349558, 0.90190234, 0.92922251, 0.9403113 ,
        0.8675916 , 0.90792097, 0.92240851, 0.9481358 , 0.93175163,
        0.938474  , 0.89920756, 0.93238335, 0.91471117, 0.91473418,
        0.88862206, 0.91007374, 0.89885913, 0.82738304],
       [0.9877132 , 0.99625498, 1.        , 0.98507766, 0.9811248 ,
        0.99578379, 0.9149563 , 0.90209161, 0.92978193, 0.94154521,
        0.86732477, 0.90820676, 0.92195579, 0.94819425, 0.93196911,
        0.93889082, 0.89862307, 0.93172695, 0.91363926, 0.91488155,
        0.88806434, 0.90955826, 0.89935643, 0.82630883],
       [0.979

In [25]:
corr

tensor([[1.0000, 0.9747, 0.9752, 0.9596, 0.9494, 0.9742, 0.8160, 0.7989, 0.8444,
         0.8819, 0.7522, 0.8200, 0.8528, 0.8893, 0.9070, 0.8823, 0.8273, 0.8767,
         0.8445, 0.8476, 0.7832, 0.8364, 0.8053, 0.7432],
        [0.9747, 1.0000, 0.9925, 0.9737, 0.9682, 0.9925, 0.8287, 0.8130, 0.8587,
         0.8987, 0.7637, 0.8358, 0.8692, 0.9077, 0.8908, 0.9036, 0.8444, 0.8979,
         0.8623, 0.8657, 0.7984, 0.8509, 0.8215, 0.7338],
        [0.9752, 0.9925, 1.0000, 0.9709, 0.9668, 0.9921, 0.8305, 0.8126, 0.8588,
         0.9016, 0.7627, 0.8363, 0.8688, 0.9081, 0.8920, 0.9053, 0.8442, 0.8978,
         0.8611, 0.8668, 0.7970, 0.8505, 0.8224, 0.7323],
        [0.9596, 0.9737, 0.9709, 1.0000, 0.9539, 0.9694, 0.8051, 0.7961, 0.8365,
         0.8653, 0.7455, 0.8036, 0.8447, 0.8826, 0.8621, 0.8668, 0.8184, 0.8649,
         0.8415, 0.8376, 0.7846, 0.8361, 0.7967, 0.7199],
        [0.9494, 0.9682, 0.9668, 0.9539, 1.0000, 0.9673, 0.7839, 0.7731, 0.8135,
         0.8645, 0.7166, 0.7856, 0.8243

In [26]:
edges_1 = []
edge_list = []
edge_weights = []

#th = 0.999
th = 0.92
for i, elem1 in enumerate(exp_values):
  for j, elem2 in enumerate(exp_values):
    #sim = sim_matrix[i][i]
    sim = corr[i, j]
    if sim > th:
      if f"{expr.T.columns[i]}_{expr.T.columns[j]}" not in edges_1:
        edges_1.append(f"{expr.T.columns[i]}_{expr.T.columns[j]}")
        edge_list.append((expr.T.columns[i], expr.T.columns[j]))
        edge_weights.append(sim)
    

In [27]:
len(edges_1)

88

In [28]:
# Parse the edges and create node mapping
source_nodes, target_nodes, node_mapping = parse_edges(edges_1)

# Print node mapping for reference
print("Node Mapping:", node_mapping)

# Create edge_index tensor
edge_index = create_edge_index(source_nodes, target_nodes)

print("Edge Index Tensor:")
print(edge_index)

Node Mapping: {'GSM928410': 0, 'GSM928411': 1, 'GSM928412': 2, 'GSM928413': 3, 'GSM928414': 4, 'GSM928415': 5, 'GSM928416': 6, 'GSM928417': 7, 'GSM928418': 8, 'GSM928419': 9, 'GSM928423': 10, 'GSM928424': 11, 'GSM928425': 12, 'GSM928427': 13, 'GSM928420': 14, 'GSM928421': 15, 'GSM928422': 16, 'GSM928426': 17, 'GSM928429': 18, 'GSM928431': 19, 'GSM928428': 20, 'GSM928430': 21, 'GSM928432': 22, 'GSM928433': 23}
Edge Index Tensor:
tensor([[ 0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
          3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,
          6,  7,  8,  9,  9,  9,  9,  9, 14, 15, 16, 16, 16, 16, 16, 10, 10, 10,
         10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 17, 17, 17, 13, 13, 13,
         13, 13, 13, 20, 20, 18, 18, 18, 18, 21, 19, 19, 19, 19, 22, 23],
        [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,
          0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,
        

In [29]:
expr.values.shape

(24, 27551)

In [30]:
edge_weights = torch.tensor(edge_weights)
edge_weights

tensor([1.0000, 0.9747, 0.9752, 0.9596, 0.9494, 0.9742, 0.9747, 1.0000, 0.9925,
        0.9737, 0.9682, 0.9925, 0.9752, 0.9925, 1.0000, 0.9709, 0.9668, 0.9921,
        0.9596, 0.9737, 0.9709, 1.0000, 0.9539, 0.9694, 0.9494, 0.9682, 0.9668,
        0.9539, 1.0000, 0.9673, 0.9742, 0.9925, 0.9921, 0.9694, 0.9673, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 0.9314, 0.9302, 0.9351, 0.9490, 1.0000,
        1.0000, 1.0000, 0.9310, 0.9218, 0.9277, 0.9351, 0.9314, 0.9310, 1.0000,
        0.9239, 0.9349, 0.9302, 1.0000, 0.9216, 0.9249, 0.9351, 0.9239, 0.9216,
        1.0000, 0.9419, 0.9330, 0.9218, 1.0000, 0.9327, 0.9490, 0.9349, 0.9249,
        0.9419, 1.0000, 0.9260, 1.0000, 0.9201, 0.9277, 0.9330, 0.9260, 1.0000,
        1.0000, 0.9351, 0.9327, 0.9201, 1.0000, 1.0000, 1.0000],
       dtype=torch.float64)

In [31]:
import pygod
from pygod.utils import load_data

x = torch.tensor(expr.values).to(device)
y = torch.tensor(clinic.values).to(device).flatten()
edge_index = edge_index.to(device)
edge_weights = edge_weights.to(device)
x.shape, y.shape, edge_index.shape

(torch.Size([24, 27551]), torch.Size([24]), torch.Size([2, 88]))

In [32]:
def ensure_tensor(data, dtype):
    if not isinstance(data, torch.Tensor):
        data = torch.tensor(data, dtype=dtype)
    elif data.dtype != dtype:
        data = data.to(dtype)
    return data

In [32]:
x = ensure_tensor(x, dtype=torch.float)
x

tensor([[4.2296, 4.8021, 4.1456,  ..., 4.2563, 4.8218, 5.0056],
        [4.1972, 4.8203, 4.1712,  ..., 4.3174, 4.5183, 4.3083],
        [4.1315, 4.6408, 4.0758,  ..., 4.2419, 4.6804, 4.7810],
        ...,
        [4.2603, 4.6196, 4.1528,  ..., 4.1952, 4.6629, 4.7324],
        [4.3019, 4.6804, 4.0996,  ..., 4.2827, 4.7398, 4.9293],
        [4.3184, 4.1952, 4.2240,  ..., 4.3487, 4.5995, 4.6141]],
       device='cuda:0')

In [33]:
y = ensure_tensor(y, dtype=torch.long)
y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')

In [34]:
edge_index = ensure_tensor(edge_index, dtype=torch.long)
edge_index

tensor([[  0,   0,   0,  ..., 119, 119, 119],
        [  0,   1,   2,  ..., 117, 118, 119]], device='cuda:0')

In [35]:
from torch_geometric.data import Data

data = Data(x=x, edge_index = edge_index, y = y)
data

Data(x=[132, 18981], edge_index=[2, 16096], y=[132])

In [36]:
print("edge_index:", edge_index)
print(f"Max node index in edge_index: {edge_index.max()}")
print(f"Min node index in edge_index: {edge_index.min()}")

# Check if any index is out of bounds
if edge_index.max() >= 132 or edge_index.min() < 0:
    raise ValueError("edge_index contains out-of-bounds indices")

edge_index: tensor([[  0,   0,   0,  ..., 119, 119, 119],
        [  0,   1,   2,  ..., 117, 118, 119]], device='cuda:0')
Max node index in edge_index: 131
Min node index in edge_index: 0


In [37]:
# Check for NaNs and infinities
assert not torch.isnan(x).any(), "Found NaNs in x"
assert not torch.isnan(edge_index).any(), "Found NaNs in edge_index"
assert not torch.isinf(edge_index).any(), "Found Infs in edge_index"
assert not torch.isinf(x).any(), "Found Infs in x"

In [38]:
data.y

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')

In [39]:
import torch
from sklearn.model_selection import train_test_split

# Assuming `data.y` contains the labels
num_nodes = data.num_nodes
train_size = 0.6  # 60% for training



# Create a boolean mask for training nodes
indices = torch.arange(num_nodes)
train_indices, test_indices = train_test_split(indices, train_size=train_size, stratify=data.y.cpu())


train_mask = torch.zeros(num_nodes, dtype=torch.bool).to(device)
test_mask = torch.zeros(num_nodes, dtype=torch.bool).to(device)
train_mask[train_indices] = True
test_mask[test_indices] = True

data.train_mask = train_mask
data.test_mask = test_mask

In [40]:
y[train_mask]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0], device='cuda:0')

In [41]:
y[test_mask]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0], device='cuda:0')

In [42]:
import pandas as pd
import torch